name: Package CI

on:
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.2 ]
        version: [ lowest, standard ]

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json

      - name: Run a one-line script
        run: echo Hello, world!
