<?php

namespace Spameri\Elastic\Diagnostics\Panel;

?>
<style>
	#nette-debug .elasticSearchPanel-method { font-weight: bold; }

	#nette-debug .elasticSearchPanel-error { font-size: xx-small; }
</style>
<h1>
	Elastic queries:
	<?= count($queries) ?> queries / <?= sprintf('%0.1f', $queriesDuration) ?>ms
</h1>
<div class="nette-inner elasticSearchPanel">
	<table>
		<thead>
		<tr>
			<th>Uri</th>
			<th>Took</th>
			<th>Request</th>
			<th>Request string</th>
			<th>Response</th>
		</tr>
		</thead>
		<tbody>
		<?php foreach ($queries as $key => $query): ?>
            <tr>
                <td><?= $query['uri'] ?></td>

                <td><?= $query['duration'] ?></td>

                <td>
                    <span class="tracy-toggle tracy-collapsed">
						<span class="tracy-dump-object">Show</span>
					</span>
                    <div class="tracy-collapsed">
		                <?= $query['requestBody'] ?>
                    </div>
                </td>

                <td>
                    <span class="tracy-toggle tracy-collapsed">
						<span class="tracy-dump-object">Show</span>
					</span>
                    <div class="tracy-collapsed">
                        <?= $query['requestBodyString'] ?>
                    </div>
                </td>

                <td>
                    <span class="tracy-toggle tracy-collapsed">
						<span class="tracy-dump-object">Show</span>
					</span>
                    <div class="tracy-collapsed">
		                <?= $query['responseBody'] ?>
                    </div>
                </td>
            </tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>
